merchant/modules/order/controllers/CustomerController.php
<?php

namespace addons\TinyShop\merchant\modules\order\controllers;

use Yii;
use yii\data\Pagination;
use yii\web\NotFoundHttpException;
use common\enums\StatusEnum;
use common\helpers\ResultHelper;
use common\models\forms\CreditsLogForm;
use addons\TinyShop\common\models\order\Customer;
use addons\TinyShop\common\models\forms\CustomerRefundForm;
use addons\TinyShop\common\models\order\OrderProduct;
use addons\TinyShop\merchant\controllers\BaseController;

/**
 * 售后
 *
 * Class CustomerController
 * @package addons\TinyShop\merchant\modules\order\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class CustomerController extends BaseController
{
    /**
     * 首页
     *
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionIndex()
    {
        $order_sn = Yii::$app->request->get('order_sn');

        $data = Customer::find()
            ->where(['>=', 'status', StatusEnum::DISABLED])
            ->andFilterWhere(['like', 'order_sn', $order_sn])
            ->andFilterWhere(['merchant_id' => $this->getMerchantId()]);

        $pages = new Pagination(['totalCount' => $data->count(), 'pageSize' => $this->pageSize]);
        $models = $data->offset($pages->offset)
            ->orderBy('id desc')
            ->limit($pages->limit)
            ->all();

        return $this->render($this->action->id, [
            'models' => $models,
            'pages' => $pages,
            'order_sn' => $order_sn,
        ]);
    }

    /**
     * 同意退款申请
     *
     * @return array
     */
    public function actionRefundPass()
    {
        $id = Yii::$app->request->post('id');

        try {
            Yii::$app->tinyShopService->orderCustomer->refundPass($id);

            return ResultHelper::json(200, '操作成功');
        } catch (\Exception $e) {
            return ResultHelper::json(422, $e->getMessage());
        }
    }

    /**
     * 拒绝退款申请
     *
     * @param $id
     * @param $always
     * @return array
     */
    public function actionRefundNoPass()
    {
        $id = Yii::$app->request->post('id');
        $always = Yii::$app->request->post('always', false);

        try {
            Yii::$app->tinyShopService->orderCustomer->refundNoPass($id, $always);

            return ResultHelper::json(200, '操作成功');
        } catch (\Exception $e) {
            return ResultHelper::json(422, $e->getMessage());
        }
    }

    /**
     * 确认退款
     *
     * @param $id
     * @return mixed|string
     * @throws NotFoundHttpException
     */
    public function actionRefundReturnMoney($id)
    {
        /** @var OrderProduct $model */
        $model = $this->findRefundModel($id);
        $order = $model->order;

        // 申请默认退款金额
        $model->refund_balance_money = Yii::$app->tinyShopService->orderProduct->getRefundBalanceMoney($order, $model);

        if ($model->load(Yii::$app->request->post())) {
            // 开启事务
            $transaction = Yii::$app->db->beginTransaction();
            try {
                // 退款进订单
                $orderProduct = Yii::$app->tinyShopService->orderCustomer->refundReturnMoney($id, false);
                // 退款进用户余额/原路退回
                Yii::$app->services->memberCreditsLog->incrMoney(new CreditsLogForm([
                    'member' => Yii::$app->services->member->get($model->member_id),
                    'num' => $orderProduct->refund_balance_money,
                    'credit_group' => 'orderRefundBalanceMoney',
                    'map_id' => $orderProduct->id,
                    'remark' => '订单售后退款',
                ]));

                $transaction->commit();

                return $this->message('操作成功', $this->redirect(Yii::$app->request->referrer));
            } catch (\Exception $e) {
                $transaction->rollBack();

                return $this->message($e->getMessage(), Yii::$app->request->referrer, 'error');
            }
        }

        return $this->renderAjax('@addons/TinyShop/merchant/modules/order/views/product/refund-return-money', [
            'product' => $model,
            'order' => $order,
        ]);
    }

    /**
     * 确认收货
     *
     * @return array
     */
    public function actionRefundDelivery()
    {
        $id = Yii::$app->request->post('id');

        try {
            Yii::$app->tinyShopService->orderCustomer->refundDelivery($id);

            return ResultHelper::json(200, '操作成功');
        } catch (\Exception $e) {
            return ResultHelper::json(422, $e->getMessage());
        }
    }

    /**
     * @param $id
     * @return string
     */
    public function actionRefundDetail($id)
    {
        return $this->render($this->action->id, [
            'model' => Yii::$app->tinyShopService->orderCustomer->findById($id),
        ]);
    }

    /**
     * @param $id
     * @return CustomerRefundForm|\yii\db\ActiveRecord
     * @throws NotFoundHttpException
     */
    public function findRefundModel($id)
    {
        /* @var $model CustomerRefundForm */
        if (empty($id) || !($model = CustomerRefundForm::find()->where([
                'id' => $id,
                'status' => StatusEnum::ENABLED,
            ])->andFilterWhere(['merchant_id' => $this->getMerchantId()])->one())) {
            throw new NotFoundHttpException('请求的数据不存在');
        }

        return $model;
    }
}

merchant/modules/order/controllers/OrderController.php
<?php

namespace addons\TinyShop\merchant\modules\order\controllers;

use Yii;
use yii\data\Pagination;
use yii\db\ActiveQuery;
use yii\web\NotFoundHttpException;
use common\enums\StatusEnum;
use common\helpers\ArrayHelper;
use common\helpers\ResultHelper;
use common\enums\PayTypeEnum;
use addons\TinyShop\common\models\order\Order;
use addons\TinyShop\common\enums\OrderStatusEnum;
use addons\TinyShop\common\enums\RefundStatusEnum;
use addons\TinyShop\merchant\forms\DeliverProductForm;
use addons\TinyShop\merchant\forms\PickupForm;
use addons\TinyShop\merchant\controllers\BaseController;

/**
 * Class OrderController
 * @package addons\TinyShop\merchant\controllers
 * @author jianyan74 <751393839@qq.com>
 */
class OrderController extends BaseController
{
    /**
     * @var Order
     */
    public $modelClass = Order::class;

    /**
     * 首页
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $order_status = Yii::$app->request->get('order_status', '');
        $order_sn = Yii::$app->request->get('order_sn');

        $data = Order::find()
            ->alias('o')
            ->where(['>=', 'o.status', StatusEnum::DISABLED])
            ->andFilterWhere(['like', 'order_sn', $order_sn])
            ->andFilterWhere(['o.merchant_id' => $this->getMerchantId()]);

        if ($order_status != RefundStatusEnum::CANCEL) {
            $data = $data->with(['member', 'product'])->andFilterWhere(['o.order_status' => $order_status]);
        } else {
            // 退款中
            $data = $data->with(['member'])->joinWith([
                'product p' => function (ActiveQuery $query) {
                    return $query->andWhere(['in', 'refund_status', RefundStatusEnum::refund()]);
                },
            ]);
        }

        $pages = new Pagination(['totalCount' => $data->count(), 'pageSize' => $this->pageSize]);
        $models = $data->offset($pages->offset)
            ->orderBy('id desc')
            ->limit($pages->limit)
            ->all();

        return $this->render($this->action->id, [
            'models' => $models,
            'pages' => $pages,
            'order_status' => $order_status,
            'order_sn' => $order_sn,
            'total' => Yii::$app->tinyShopService->order->getCount(),
        ]);
    }

    /**
     * @param $id
     * @return string
     */
    public function actionDetail($id)
    {
        $model = Order::find()
            ->where(['>=', 'status', StatusEnum::DISABLED])
            ->andWhere(['id' => $id])
            ->andFilterWhere(['merchant_id' => $this->getMerchantId()])
            ->with(['member', 'product', 'company', 'invoice', 'pickup', 'productExpress'])
            ->one();

        $product = ArrayHelper::toArray($model->product);
        $productExpress = ArrayHelper::toArray($model->productExpress);

        // 重组发货
        foreach ($productExpress as &$express) {
            $express['product'] = [];

            foreach ($product as $key => $item) {
                if (in_array($item['id'], $express['order_product_ids'])) {
                    $express['product'][] = $item;
                    unset($product[$key]);
                }
            }
        }

        return $this->render($this->action->id, [
            'model' => $model,
            'product' => $product,
            'productExpress' => $productExpress,
            'orderAction' => Yii::$app->tinyShopService->orderAction->findByOrderId($id),
        ]);
    }

    /**
     * 备注
     *
     * @param $id
     * @return mixed|string
     * @throws NotFoundHttpException
     * @throws \yii\base\ExitException
     */
    public function actionSellerMemo($id)
    {
        $model = $this->findModel($id);

        $this->activeFormValidate($model);
        if ($model->load(Yii::$app->request->post())) {
            return $model->save()
                ? $this->message('修改成功', $this->redirect(Yii::$app->request->referrer))
                : $this->message($this->getError($model), $this->redirect(Yii::$app->request->referrer), 'error');
        }

        return $this->renderAjax($this->action->id, [
            'model' => $model,
        ]);
    }

    /**
     * 收货地址
     *
     * @param $id
     * @return mixed|string
     * @throws NotFoundHttpException
     * @throws \yii\base\ExitException
     */
    public function actionAddress($id)
    {
        $model = $this->findModel($id);

        $this->activeFormValidate($model);
        if ($model->load(Yii::$app->request->post())) {
            $model->receiver_region_name = Yii::$app->services->provinces->getCityListName([
                $model->receiver_province,
                $model->receiver_city,
                $model->receiver_area,
            ]);

            return $model->save()
                ? $this->message('修改成功', $this->redirect(Yii::$app->request->referrer))
                : $this->message($this->getError($model), $this->redirect(Yii::$app->request->referrer), 'error');
        }

        return $this->renderAjax($this->action->id, [
            'model' => $model,
        ]);
    }

    /**
     * 线下支付
     *
     * @param $id
     * @return mixed
     */
    public function actionPay($id)
    {
        try {
            $order = $this->findModel($id);
            Yii::$app->tinyShopService->order->pay($order, PayTypeEnum::OFFLINE);

            // 记录操作
            Yii::$app->tinyShopService->orderAction->create(
                '订单支付',
                $order->id,
                $order->order_status,
                Yii::$app->user->identity->id,
                Yii::$app->user->identity->username
            );

            return $this->message('线下支付成功', $this->redirect(Yii::$app->request->referrer));
        } catch (\Exception $e) {
            return $this->message($e->getMessage(), $this->redirect(Yii::$app->request->referrer), 'error');
        }
    }

    /**
     * 关闭订单
     *
     * @param $id
     * @return array
     */
    public function actionClose($id)
    {
        try {
            Yii::$app->tinyShopService->order->close($id);

            return ResultHelper::json(200, '操作成功');
        } catch (\Exception $e) {
            return ResultHelper::json(422, $e->getMessage());
        }
    }

    /**
     * 确认收货
     *
     * @param $id
     * @return array
     */
    public function actionTakeDelivery($id)
    {
        try {
            Yii::$app->tinyShopService->order->takeDelivery($id);

            return ResultHelper::json(200, '操作成功');
        } catch (\Exception $e) {
            return ResultHelper::json(422, $e->getMessage());
        }
    }


    /**
     * 提货
     *
     * @param $id
     * @return mixed|string
     * @throws NotFoundHttpException
     * @throws \yii\base\ExitException
     */
    public function actionPickup($id)
    {
        $order = $this->findModel($id);
        $model = PickupForm::findOne(['order_id' => $order->id]);

        // ajax校验
        $this->activeFormValidate($model);
        if ($model->load(Yii::$app->request->post())) {
            // 进行无物流状态
            $deliverProduct = new DeliverProductForm();
            $deliverProduct->order = $order;
            $deliverProduct->member_id = Yii::$app->user->identity->id;
            $deliverProduct->member_username = Yii::$app->user->identity->username;
            $deliverProduct->shipping_type = DeliverProductForm::SHIPPING_TYPE_NOT_LOGISTICS;
            $deliverProduct->order_product_ids = ArrayHelper::getColumn($order->product, 'id');

            // 事务
            $transaction = Yii::$app->db->beginTransaction();
            try {
                if (!$model->save()) {
                    throw new NotFoundHttpException($this->getError($model));
                }

                if (!$deliverProduct->save()) {
                    throw new NotFoundHttpException($this->getError($deliverProduct));
                }

                // 进行收货
                Yii::$app->tinyShopService->order->takeDelivery($id);

                $transaction->commit();

                return $this->message('提货成功', $this->redirect(Yii::$app->request->referrer));
            } catch (\Exception $e) {
                $transaction->rollBack();

                return $this->message($e->getMessage(), $this->redirect(Yii::$app->request->referrer), 'error');
            }
        }

        return $this->renderAjax($this->action->id, [
            'model' => $model,
        ]);
    }

    /**
     * 伪删除
     *
     * @param $id
     * @return mixed
     */
    public function actionDestroy($id)
    {
        if (!($model = $this->modelClass::findOne($id))) {
            return $this->message("找不到订单", $this->redirect(['index']), 'error');
        }

        // 非关闭订单不可删除
        if ($model->order_status != OrderStatusEnum::REPEAL) {
            return $this->message("删除失败", $this->redirect(['index']), 'error');
        }

        $model->status = StatusEnum::DELETE;
        if ($model->save()) {
            return $this->message("删除成功", $this->redirect(['index']));
        }

        return $this->message("删除失败", $this->redirect(['index']), 'error');
    }

    /**
     * @param $id
     * @return Order
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        /* @var $model Order */
        if (empty($id) || empty(($model = $this->modelClass::findOne([
                'id' => $id,
                'merchant_id' => $this->getMerchantId()
            ])))) {
            throw new NotFoundHttpException('找不到订单');
        }

        return $model;
    }
}

merchant/modules/order/views/customer/index.php
<?php

use common\helpers\Url;
use yii\widgets\LinkPager;
use common\enums\PayTypeEnum;
use common\helpers\Html;
use addons\TinyShop\common\helpers\OrderHelper;
use addons\TinyShop\common\enums\RefundStatusEnum;
use addons\TinyShop\common\enums\AccessTokenGroupEnum;

$this->title = '售后服务';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"><?= $this->title; ?></h3>
                <div class="box-tools">

                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>商品信息</th>
                        <th>商品清单</th>
                        <th>订单金额</th>
                        <th>收货信息</th>
                        <th>买家</th>
                        <th>交易状态</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($models as $model) { ?>
                        <tr>
                            <td colspan="8">
                                <span class="fa fa-angle-down"></span>
                                订单编号：<?= $model->order_sn; ?>
                                <div class="pull-right">
                                    下单时间：<?= Yii::$app->formatter->asDatetime($model->created_at) ?>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <small><?= $model['product_name']; ?></small>
                                <br>
                                <small style="color: #999"><?= $model['sku_name']; ?></small>
                            </td>
                            <td>
                                <span class="pull-left"><?= $model['price']; ?>元</span>
                                <span class="pull-right"><?= $model['num']; ?>件</span><br>
                                <?= OrderHelper::refundOperation($model['id'], $model['refund_status'], '')?>
                            </td>
                            <td style="text-align: center">
                                <span class="orange"><?= Yii::$app->formatter->asDecimal($model->product_money, 2); ?></span><br>
                                <small><?= PayTypeEnum::getValue($model['payment_type']) ?></small>
                            </td>
                            <td>
                                <?= $model->receiver_name; ?><br>
                                <?= $model->receiver_mobile; ?><br>
                                <?= $model->receiver_region_name; ?> <?= $model->receiver_address; ?>
                            </td>
                            <td style="text-align: center">
                                <?= $model->user_name; ?> <br>
                                <span class="blue" style="font-size: 12px"><?= AccessTokenGroupEnum::getValue($model->order_from); ?></span>
                            </td>
                            <td>
                                <?= RefundStatusEnum::getValue($model['refund_status'])?>
                            </td>
                            <td>
                                <?= Html::linkButton(['order/detail', 'id' => $model->order_id], '订单详情', [
                                    'class' => 'cyan',
                                ]) ?>
                            </td>
                        </tr>
                        <?php if(!empty($model->seller_memo)) { ?>
                            <tr>
                                <td colspan="7">
                                    卖家备注：<?= $model->seller_memo; ?>
                                </td>
                            </tr>
                        <?php } ?>
                        <tr style="background-color: #ecf0f5;"><td colspan="8"></td></tr>
                    <?php } ?>
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-sm-12">
                        <?= LinkPager::widget([
                            'pagination' => $pages,
                            'maxButtonCount' => 5,
                        ]); ?>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
</div>

<script>
    var orderProductAgreeUrl = "<?= Url::to(['refund-pass']); ?>";
    var orderProductRefuseUrl = "<?= Url::to(['refund-no-pass']); ?>";
    var orderProductDeliveryUrl = "<?= Url::to(['refund-delivery']); ?>";
</script>

merchant/modules/order/views/customer/refund-detail.php
<?php

use common\helpers\ImageHelper;
use addons\TinyShop\common\enums\RefundStatusEnum;
use addons\TinyShop\common\enums\RefundTypeEnum;

$this->title = '订单详情';
$this->params['breadcrumbs'][] = ['label' => '订单管理', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

?>

<div class="ns-main">
    <div class="mod-table">
        <div class="step-region">
            <ul class="ui-step">
                <li class="<?= $model->refund_status > 0 ? 'ui-step-done' : '';?>  col-lg-4">
                    <div class="ui-step-title">买家申请退款</div>
                    <div class="ui-step-number">1</div>
                    <div class="ui-step-meta"><?= !empty($model->refund_time) ? Yii::$app->formatter->asDatetime($model->refund_time) : '';?></div>
                </li>
                <li class="<?= $model->refund_status > RefundStatusEnum::APPLY ? 'ui-step-done' : '';?>  col-lg-4">
                    <div class="ui-step-title">商家退款处理</div>
                    <div class="ui-step-number">2</div>
                    <div class="ui-step-meta"></div>
                </li>
                <li class="<?= $model->refund_status == RefundStatusEnum::CONSENT ? 'ui-step-done' : '';?>  col-lg-4">
                    <div class="ui-step-title">退款完成</div>
                    <div class="ui-step-number">3</div>
                    <div class="ui-step-meta"></div>
                </li>
            </ul>
        </div>
        <div class="step-region clearfix">
            <div class="info-region">
                <div class="info-div">退款信息</div>
                <div>
                    <div class="info-goods">
                        <div class="ui-centered-image">
                            <img src="<?= ImageHelper::default($model['product_picture']) ?>" width="45" height="45">
                        </div>
                        <div class="info-goods-content">
                            <div><?= $model['product_name'] ?> - <?= $model['sku_name'] ?> </div>
                        </div>
                    </div>
                    <div class="dashed-line"></div>
                </div>
                <table class="info-table">
                    <tbody>
                    <tr>
                        <th>退款方式：</th>
                        <td>
                            <span class="orange"><?= RefundTypeEnum::getValue($model['refund_type']) ?></span>
                        </td>
                    </tr>
                    <tr>
                        <th>申请退款：</th>
                        <td><span class="orange"><?= $model['refund_require_money'] ?></span>元</td>
                    </tr>
                    <tr>
                        <th>退还余额：</th>
                        <td><span class="orange"><?= $model['refund_balance_money'] ?></span>元</td>
                    </tr>
                    <tr>
                        <th>退款原因：</th>
                        <td><?= $model['refund_reason'] ?? '买/卖双方协商一致' ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="state-region">
                <div style="padding: 0 0 30px 40px;" id="<?= $model['id'] ?>">
                    <div class="state-title"><span class="icon info">!</span>订单状态：<?= RefundStatusEnum::getValue($model['refund_status']) ?></div>
                </div>
                <div class="state-remind-region">
                    <div class="dashed-line"></div>
                    <div class="state-remind">
                        <div class="tixing">提醒：</div>
                        <ul>
                            <li>如果无法发货，请及时与买家联系并说明情况后进行退款；</li>
                            <li>买家申请退款后，须征得买家同意后再发货，否则买家有权拒收货物；</li>
                            <li>买家付款后超过7天仍未发货，将有权申请客服介入发起退款维权；</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="step-region safeguard-log">
            <div class="info-div">协商记录</div>
            <table class="hide">
                <tbody>
                <tr class="tr-title">
                    <td>买家</td>
                    <td class="td-time">2019-06-27 10:01:10</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <span>【买家申请退款】</span>
                    </td>
                </tr>
                </tbody>
                <tbody>
                <tr class="tr-title">
                    <td>卖家</td>
                    <td class="td-time">2019-06-27 10:01:35</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <span>【退款申请不通过】</span>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>